### ISSUE TITLE
undefined local variable or method `verify_mode'

### ISSUE THREAD

**Issue by 030** [sensu-plugins/sensu-plugins-uchiwa#5]
Running

```
/opt/sensu/embedded/bin/check-uchiwa-health.rb
```

results in:

```
[user@host ~]$ /opt/sensu/embedded/bin/check-uchiwa-health.rb -h localhost
Check failed to run: undefined local variable or method `verify_mode' for #<UchiwaHealthCheck:0x00000001b8d250>, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-uchiwa-0.0.4/bin/check-uchiwa-health.rb:82:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.3.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

**Comment by Esity** [comment]
Same issue here

**Comment by solounaletra** [comment]
Same here with Sensu 0.26.1 and its embedded Ruby 2.3.0

**Comment by cstadach** [comment]
This issue was fixed with #7

**Comment by luckymike** [comment]
Could we get a release with the fix, please?

**Comment by eheydrick** [comment]
1.0.0 has been released with the fix.
